# Generated by Django 2.2.6 on 2020-03-18 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clockIn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclockinfo',
            name='endTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userclockinfo',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
