# Generated by Django 2.1.1 on 2018-09-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boring', '0002_textinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='textLinkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=150)),
            ],
        ),
    ]
