# Generated by Django 2.1.1 on 2018-09-25 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boring', '0003_textlinkuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodmodel',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='moodtextmodel',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='textinput',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='textlinkuser',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
