# Generated by Django 2.1.1 on 2018-11-20 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boring', '0005_textlinkmood'),
    ]

    operations = [
        migrations.CreateModel(
            name='textLinkKiding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=150)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
